### ISSUE TITLE
Remove high padding in code listings

### ISSUE THREAD

**Issue by maxstoyanov** [neos/Neos.DocsNeosIo#11]
Our code listings have a high `padding-left` which is quite unhandy on mobile devices and our YAML files already have a lot of whitespace at the beginning...

This is affected through the following lines:
```css
pre[class*="language-"].line-numbers {
  position: relative; 
  padding-left: 3.8em;
  counter-reset: linenumber;
}
```
